### ISSUE TITLE
`express.text()` middleware overrides other content types

### ISSUE THREAD

**Issue by cat-ninja** [testinggospels/camouflage#232]
**Describe the bug**
While trying to integrate a middleware for requests with `multipart/form-data` content type I kept seeing `PayloadTooLargeError: request entity too large` error coming from express despite it had `multer` middleware installed and configured to accept files of any size.

Here is the stack trace:
```
PayloadTooLargeError: request entity too large
    at readStream (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/raw-body/index.js:156:17)
    at getRawBody (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/raw-body/index.js:109:12)
    at read (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/body-parser/lib/read.js:79:3)
    at textParser (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/body-parser/lib/types/text.js:86:5)
    at Layer.handle [as handle_request] (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:328:13)
    at /Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:280:10)
    at urlencodedParser (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:328:13)
    at /Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/Users/test/.nvm/versions/node/v20.2.0/lib/node_modules/camouflage-server/node_modules/body-parser/lib/types/json.js:119:7)
```

At the 4th line from the top I noticed the error is coming from `textParser`, which, I assume, is called internally by the `text()` middleware. Going trough the sources I noticed that `type` configuration for the `text` middleware is configured to return `true` by [default](https://github.com/testinggospels/camouflage/blob/29a6bb35eaec80a52b64cd0ef061f7684718348a/src/index.ts#L51).
So right now this middleware will be responsible for processing everything that is not `application/json` or `application/x-www-form-urlencoded`. 

I see two possible solutions here:
1. Change the `type` to a wildcard such as `text/*`, so it wont override any other content types middlewares.
2. Add a `limit` option to the `text` middleware with some size (ie `limit: '100mb'`) so it'll be possible to accept relatively big files.

@shubhendumadhukar what do you think?

**To Reproduce**
1. Create a POST mock that'll return anything
```
HTTP/1.1 200 OK
Content-Type: application/json

{}
```

2. Create a GET mock with content
```
HTTP/1.1 200 OK
Content-Type: text/html

<html>

<body>
  <form action="path to your post mock" method="post" enctype="multipart/form-data">
    <input type="file" name="myFile" />
    <button type="submit">Submit</button>
  </form>
</body>

</html>
```

3. Open the url of your GET mock in the browser and try to upload a file bigger than 100kb
4. Check the camouflage logs

**Comment by cat-ninja** [comment]
@shubhendumadhukar do you feel comfortable switching the text middleware config to a wildcard? I can prepare a PR.

**Comment by shubhendumadhukar** [comment]
Sure, go ahead. I was actually looking into ways to make it a configurable input, but haven't been able to give it much thought.

**Comment by cat-ninja** [comment]
https://github.com/testinggospels/camouflage/pull/234
