### ISSUE TITLE
[Help wanted] Cannot resolve/handle imports within grpc/protos during startup

### ISSUE THREAD

**Issue by ankitanallana-livongo** [testinggospels/camouflage#80]
**Describe the bug**
I have a proto file protocolVersion.proto which has an import statement like 
```
...
import "com/company/foo/package/types/semanticVersion.proto"
...
```
Both proto files A.proto and B.proto are in the `grpc/protos` directory but when I try to startup Camouflage I see this error:

```
/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/namespace.js:411
        throw Error("no such Type or Enum '" + path + "' in " + this);
        ^

Error: no such Type or Enum 'SemanticVersion' in Type .com.company.foo.package.types.ProtocolVersion
    at Type.lookupTypeOrEnum (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/namespace.js:411:15)
    at Field.resolve (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/field.js:268:94)
    at Type.set (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/type.js:177:38)
    at Type.get (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/type.js:155:45)
    at Field.resolve (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/field.js:317:21)
    at Type.resolveAll (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/namespace.js:308:25)

```
I tried putting `semanticVersion.proto` in its own folder structure but i still couldn't find it. Should I be doing something else instead?

**To Reproduce**
1. Create proto file A, proto file B in some package. Import B in A
2. Startup camouflage

**Expected behavior**
Imports can be resolved/starts up correctly

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version: 0.5.5

**Comment by shubhendumadhukar** [comment]
Could you please attach the proto files here? Please strip sensitive data, if any.

**Comment by ankitanallana-livongo** [comment]
Sure! Let me try my best - Apologies if it feels like too much - I've tried to cut down to the bare minimum:

`baz.proto`:

```
syntax = "proto3";

package com.company.protobuf.foo.bar.xyz;

import "company/protobuf/foo/bar/xyz/baz/send_users.proto";

// APIs for Baz
service Baz {
    // Redirect users
    rpc SendUser (baz.SendUserRequest) returns (baz.SendUserResponse) {
    }
}

```
`send_users.proto`:
```
syntax = "proto3";

package com.company.protobuf.foo.bar.xyz.baz;

import "company/protobuf/common/types/protocolVersion.proto";

// SendUserRequest
message SendUserRequest {
    company.protobuf.common.types.ProtocolVersion protocol_version = 1;
    string user_id = 2;
}

// SendUserResponse
message SendUserResponse {
    com.livongo.protobuf.common.types.ProtocolVersion protocol_version = 1;
    string user_value = 2;
}
```
`protocolVersion.proto`:
```
syntax = "proto3";

package company.protobuf.common.types;

import "company/protobuf/common/types/semanticVersion.proto";

// Facilitates detection of version skew between client and server
message ProtocolVersion {
    string project = 1;
    SemanticVersion version = 2;
}
```
`semanticVersion.proto`:
```
syntax = "proto3";

package com.company.protobuf.common.types;

//Semantic versioning
message SemanticVersion {
    int32 major = 1;
    int32 minor = 2;
    int32 patch = 3;
}
```

**Comment by shubhendumadhukar** [comment]
I was able to get around the types error by substituting the import paths as absolute paths.

### Directory Structure
<img width="546" alt="Screenshot 2021-07-30 at 7 29 18 AM" src="https://user-images.githubusercontent.com/10685907/127589279-dcfbef0a-56c6-4fe4-9800-1ec0ffbf507a.png">

### Change Import Paths and Refactor Type
- Used absolute paths for `send_users.proto`, `protocolVersion.proto` and `semanticVersion.proto`
- I also replaced `company.protobuf.common.types.ProtocolVersion` in `send_users.proto` with just `ProtocolVersion`.

### Mock
- Created one mock file as: `grpc/mocks/com/company/protobuf/foo/bar/xyz/Baz/SendUser.mock`
- Content/Expected Response
```json
{
  "protocol_version": {
    "project": "some-project",
    "version": {
      "major": 1,
      "minor": 1,
      "patch": 1
    }
  },
  "user_value": "some_value"
}
```

### Outcome
While I am not getting any errors, and debug logs show correct mock file and content being picked up, I am not getting the expected response on the client side. Could you please confirm the following?:
- Is the expected response correct?
- Are the changes I made, wrt import paths and types refactoring, acceptable to you?

**Comment by shubhendumadhukar** [comment]
I was finally able to get it working!

Camouflage uses default options provided by [proto-loader](https://www.npmjs.com/package/@grpc/proto-loader), which was causing the issue (specifically `keepCase: true` is something that worked for me, still figuring out why it worked).

There needs to be a way to override those default options, I'll work on that and publish a new release soon.

**Comment by ankitanallana-livongo** [comment]
Hi @shubhendumadhukar : The expected response is correct. The refactoring changes do work for me, but that means I'd have to refactor a lot of proto files :) If the imports could be resolved as is, it would be super helpful! :)

**Comment by shubhendumadhukar** [comment]
Working on #81 

That should make it possible to avoid refacing altogether. Will update by tomorrow.

**Comment by shubhendumadhukar** [comment]
@ankitanallana-livongo : Please validate the same setup you were using earlier, with latest version of Camouflage (0.5.6).

Note that you'd have to create an additional `plconfig.js` file at the root of your project which exports a variable `plconfig`.
```javascript
module.exports.plconfig = {
    keepCase: true,
    includeDirs: ["./grpc/protos/com"]
}
```
The includeDirs array should include the directory containing the imports. eg. `import "company/protobuf/foo/bar/xyz/baz/send_users.proto";` should have a corresponding entry matching the parent directory of this import in the `includeDirs` array which in this case would be `./grpc/protos/com`. More information regarding all configurable options can be found [here](https://www.npmjs.com/package/@grpc/proto-loader)

**Comment by ankitanallana-livongo** [comment]
Hi @shubhendumadhukar - I am not sure if I've missed something - I added the `plconfig.js` file with the correct `includeDirs`. During startup, I see logs like:
```
...
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/fhir/proto/r4/core/valuesets.proto
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/fhir/proto/r4/google_extensions.proto
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/fhir/proto/r4/qicore/codes.proto
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/fhir/proto/r4/qicore/qicore.proto
...
```
No failures, exceptions at all (which is great!). However, I no longer see the final startup message like `Now serving on localhost:8080 for HTTP` or `localhost:4312 for gRPC` with the flag emojis. I navigate to `localhost:8080` on my browser and I see nothing loading. 

The final debug log message I see is this:
```
...
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/protobuf/wrappers.proto
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/type/date.proto
```
Nothing more after this. Here's the concise log:
```
% camouflage --config config.yml
2021-08-02 10:18:08 debug: Camouflage configuration:
========
mocks_dir | ws.mocks_dir | http.port | http.enable | https.enable | http2.enable | grpc.enable | ws.enable | cache.enable | injection.enable | origins | ssl.key | ssl.cert | https.port | http2.port | grpc.host | grpc.port | grpc.mocks_dir | grpc.protos_dir | loglevel | backup.enable | backup.cron | configFile | ext_helpers | cache.ttl_seconds
========
./mocks | ./ws_mocks | 8080 | true | false | false | true | false | false | true | http://localhost:3000/,http://localhost:3001/,http://localhost:5000/ |  | [object Object] | ./certs/server.key | ./certs/server.cert | 8443 | 8081 | 8082 | localhost | 4312 | ./grpc/mocks | ./grpc/protos | debug | true | 0 * * * * | config.yml | ./custom_handlebar.json | 300
========

2021-08-02 10:18:08 info: [1701] Master Started
2021-08-02 10:18:08 info: Cluster metrics server listening to 5555, metrics exposed on http://localhost:5555/metrics
(node:1701) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
2021-08-02 10:18:09 info: CORS enabled for http://localhost:3000/, http://localhost:3001/, http://localhost:5000/
2021-08-02 10:18:09 info: [1726] Worker started
2021-08-02 10:18:09 info: Handlebar helpers registration started
2021-08-02 10:18:09 warn: Code Injection is enabled.
2021-08-02 10:18:09 error: Loading custom handlebar helpers from ./custom_handlebar.json failed. File not found.
2021-08-02 10:18:09 info: Handlebar helpers registration completed
2021-08-02 10:18:09 debug: Using proto-loader config as: {"keepCase":true,"includeDirs":["./grpc/protos/es"]}
2021-08-02 10:18:09 debug: Ignoring protofiles:
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/blog.proto
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/api/annotations.proto
... (more logs which find more protofiles)
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/protobuf/wrappers.proto
2021-08-02 10:18:09 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/type/date.proto
```
The `config.yml` file is only different in two parameters: `loglevel: debug` and the `grpc` `enable: true` (I have been working with this `config.yml` all this time.

Any ideas why I might be seeing this?

**Comment by ankitanallana-livongo** [comment]
Hello @shubhendumadhukar Camouflage starts up okay but it takes a very very long time to start up. Easily 15-20 mins 😔

**Comment by shubhendumadhukar** [comment]
@ankitanallana-livongo : Please raise another issue, I will look into it.

I am however not sure if I can recreate the issue. The number of protofiles could be a factor. There is a recursive function that might be the culprit. 

Meanwhile, you could try using the `.protoignore` file at the root of your project. Provide the paths of the protofiles which have been used as imports in other protofiles. It should reduce some time during the startup.

**Comment by ankitanallana-livongo** [comment]
Surely! I'll try that - many thanks!

**Comment by ankitanallana-livongo** [comment]
@shubhendumadhukar  I've been trying different variations but haven't been successful - I see the following error:

```
2021-08-02 16:16:11 debug: Found protofile: /Users/ankita.nallana/camo/grpc/protos/es/google/type/date.proto
/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/root.js:104
            throw err;
            ^

Error: illegal token './grpc/protos/todoEnum.proto' (/Users/ankita.nallana/camo/grpc/protos/.protoignore, line 1)
    at illegal (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/parse.js:96:16)
    at parse (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/parse.js:796:23)
    at process (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/root.js:178:13)
    at Root.load (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/root.js:206:13)
    at Root.loadSync (/usr/local/lib/node_modules/camouflage-server/node_modules/protobufjs/src/root.js:247:17)
    at Object.loadProtosWithOptionsSync (/usr/local/lib/node_modules/camouflage-server/node_modules/@grpc/proto-loader/build/src/util.js:66:29)
    at Object.loadSync (/usr/local/lib/node_modules/camouflage-server/node_modules/@grpc/proto-loader/build/src/index.js:191:31)
    at /usr/local/lib/node_modules/camouflage-server/dist/protocols/index.js:110:46
    at Array.forEach (<anonymous>)

```

**Comment by shubhendumadhukar** [comment]
The `.protoignore` file needs to be at the root of your project. Current path shows `..../camo/grpc/protos/.protoignore`, while it should just be `..../camo/.protoignore`

Closing this issue, I have made some fixes to reduce the startup time. We'll continue further triage on the relevant issue.
